services:
  kafka-b:
    image: docker.io/apache/kafka:4.0.1
    container_name: kafka-b
    ports:
      - "9092:9092"
      - "9094:9094"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093,EXTERNAL://0.0.0.0:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-b:9092,EXTERNAL://localhost:9094
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-b:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs

  mongo:
    container_name: mongo
    image: docker.io/mongo:8.0.15
    ports:
      - "${MONGO_PORT}:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}

  postgres:
    build:
      context: .
      dockerfile: docker/postgres/Dockerfile
    container_name: db-container
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ./docker/postgres/init:/docker-entrypoint-initdb.d

  auth-service:
    image: localhost/identity-service:1.0.0
    container_name: auth-service
    ports:
      - "${BEAT_IDENTITY_SERVER}:${BEAT_IDENTITY_SERVER}"
    env_file:
      - .env
    environment:
      - POSTGRES_DB=identity-db

  messaging-service:
    image: localhost/messaging-service:1.0.0
    container_name: messaging-service
    ports:
      - "${BEAT_MESSASSING_SERVER}:${BEAT_MESSASSING_SERVER}"
    env_file:
      - .env
    environment:
      - POSTGRES_DB=messaging-db

  core-service:
    image: localhost/core-service:1.0.0
    container_name: core-service
    ports:
      - "${BEAT_API_REST_PORT}:${BEAT_API_REST_PORT}"
    env_file:
      - .env
    environment:
      - POSTGRES_DB=core-db
