services:
  kafka-b:
    image: docker.io/apache/kafka:4.0.1
    container_name: kafka-b
    ports:
      - "9092:9092"
      - "9094:9094"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093,EXTERNAL://0.0.0.0:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-b:9092,EXTERNAL://localhost:9094
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-b:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
    healthcheck:
      test: ["CMD", "bash", "-c", "echo > /dev/tcp/localhost/9092"]
      interval: 5s
      timeout: 2s
      retries: 10

  mongo:
    container_name: mongo
    image: docker.io/mongo:8.0.15
    ports:
      - "${MONGO_PORT}:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}
    healthcheck:
      test: ["CMD", "bash", "-c", "echo > /dev/tcp/localhost/27017"]
      interval: 5s
      timeout: 2s
      retries: 10

  postgres:
    build:
      context: .
      dockerfile: docker/postgres/Dockerfile
    container_name: db-container
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ./docker/postgres/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 10

  proxy:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: proxy
    env_file:
      - .env
    ports:
      - "${PROXY_PORT}:${PROXY_PORT}"
    depends_on:
      - auth-service
      - messaging-service
      - core-service

  auth-service:
    image: identity-service:1.0.0
    container_name: auth-service
    env_file:
      - .env
    environment:
      - POSTGRES_DB=identity_db
    depends_on:
      postgres:
        condition: service_healthy
      kafka-b:
        condition: service_healthy

  messaging-service:
    image: messaging-service:1.0.0
    container_name: messaging-service
    env_file:
      - .env
    environment:
      - POSTGRES_DB=messaging_db
    depends_on:
      postgres:
        condition: service_healthy
      kafka-b:
        condition: service_healthy
      mongo:
        condition: service_healthy

  core-service:
    image: core-service:1.0.0
    container_name: core-service
    env_file:
      - .env
    environment:
      - POSTGRES_DB=core_db
    depends_on:
      postgres:
        condition: service_healthy
      kafka-b:
        condition: service_healthy

